### ISSUE TITLE
Predicting response to new drugs

### ISSUE THREAD

**Issue by mingjiang7940** [CompBioT/SCAD#3]
Hi，

Thank you for developing SCAD – it's a nice tool, and  I am very interested in it!
Does it support training new drug response labels on my bulk data, and if so, how should I train new drug labels and use it to predict single-cell datasets?
@CompBioT 

Best,
Cheng

**Comment by CompBioT** [comment]
Sorry for the late reply. Technically, it can be applied to predict other/new single-cell datasets. GDSC contains many drugs with well-annotated drug response labels, and part of them can also be found in the SCAD/data/response folder. If you have your own bulk data with drug response labels, you can create your source domain training data similar to the format in SCAD/data/original_norm, then use split_data_SCAD_5fold_norm.py to split your data to serve as input for SCAD and get the predict drug response scores of cells for your single-cell datasets.

**Comment by mingjiang7940** [comment]
Thank you, I have been able to use it successfully!
